"""initial schema

Revision ID: c2245193093b
Revises:
Create Date: 2026-08-02 15:44:29.747751

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "c2245193093b"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_events",
        sa.Column("event_id", sa.String(length=64), nullable=False),
        sa.Column("job_id", sa.String(length=64), nullable=True),
        sa.Column("event_type", sa.String(length=48), nullable=False),
        sa.Column("actor_type", sa.String(length=32), nullable=False),
        sa.Column("actor_id", sa.String(length=128), nullable=False),
        sa.Column("payload_redacted_json", sa.JSON(), nullable=False),
        sa.Column("previous_event_hash", sa.String(length=80), nullable=True),
        sa.Column("event_hash", sa.String(length=80), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("event_id"),
    )
    with op.batch_alter_table("audit_events", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_audit_events_job_id"), ["job_id"], unique=False)

    op.create_table(
        "documents",
        sa.Column("document_id", sa.String(length=64), nullable=False),
        sa.Column("path_hash", sa.String(length=80), nullable=False),
        sa.Column("fingerprint", sa.String(length=80), nullable=True),
        sa.Column("current_revision", sa.String(length=80), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("document_id"),
    )
    op.create_table(
        "entity_mappings",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("document_id", sa.String(length=64), nullable=False),
        sa.Column("feature_id", sa.String(length=128), nullable=False),
        sa.Column("operation_id", sa.String(length=160), nullable=False),
        sa.Column("entity_ref", sa.String(length=128), nullable=False),
        sa.Column("last_revision", sa.String(length=80), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("document_id", "entity_ref", name="uq_entity_mapping_ref"),
    )
    with op.batch_alter_table("entity_mappings", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_entity_mappings_document_id"), ["document_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_entity_mappings_feature_id"), ["feature_id"], unique=False
        )

    op.create_table(
        "jobs",
        sa.Column("job_id", sa.String(length=64), nullable=False),
        sa.Column("document_id", sa.String(length=64), nullable=False),
        sa.Column("state", sa.String(length=32), nullable=False),
        sa.Column("expected_revision", sa.String(length=80), nullable=False),
        sa.Column("current_spec_version", sa.Integer(), nullable=False),
        sa.Column("plan_hash", sa.String(length=80), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.document_id"],
        ),
        sa.PrimaryKeyConstraint("job_id"),
    )
    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_jobs_plan_hash"), ["plan_hash"], unique=False)

    op.create_table(
        "approvals",
        sa.Column("approval_id", sa.String(length=64), nullable=False),
        sa.Column("job_id", sa.String(length=64), nullable=False),
        sa.Column("plan_hash", sa.String(length=80), nullable=False),
        sa.Column("expected_revision", sa.String(length=80), nullable=False),
        sa.Column("approved_by", sa.String(length=128), nullable=False),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked", sa.Boolean(), nullable=False),
        sa.Column("record_json", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["jobs.job_id"],
        ),
        sa.PrimaryKeyConstraint("approval_id"),
    )
    op.create_table(
        "checkpoints",
        sa.Column("checkpoint_id", sa.String(length=64), nullable=False),
        sa.Column("job_id", sa.String(length=64), nullable=False),
        sa.Column("revision", sa.String(length=80), nullable=False),
        sa.Column("artifact_ref", sa.Text(), nullable=False),
        sa.Column("byte_size", sa.Float(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["jobs.job_id"],
        ),
        sa.PrimaryKeyConstraint("checkpoint_id"),
    )
    op.create_table(
        "executions",
        sa.Column("execution_id", sa.String(length=64), nullable=False),
        sa.Column("job_id", sa.String(length=64), nullable=False),
        sa.Column("idempotency_key", sa.String(length=128), nullable=False),
        sa.Column("request_digest", sa.String(length=80), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("result_json", sa.JSON(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["jobs.job_id"],
        ),
        sa.PrimaryKeyConstraint("execution_id"),
        sa.UniqueConstraint("job_id", "idempotency_key", name="uq_execution_idempotency"),
    )
    op.create_table(
        "plans",
        sa.Column("plan_id", sa.String(length=64), nullable=False),
        sa.Column("job_id", sa.String(length=64), nullable=False),
        sa.Column("schema_version", sa.String(length=16), nullable=False),
        sa.Column("plan_json", sa.JSON(), nullable=False),
        sa.Column("plan_hash", sa.String(length=80), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["jobs.job_id"],
        ),
        sa.PrimaryKeyConstraint("plan_id"),
        sa.UniqueConstraint("plan_hash"),
    )
    op.create_table(
        "spec_versions",
        sa.Column("spec_version_id", sa.String(length=64), nullable=False),
        sa.Column("job_id", sa.String(length=64), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("schema_version", sa.String(length=16), nullable=False),
        sa.Column("normalized_json", sa.JSON(), nullable=False),
        sa.Column("content_hash", sa.String(length=80), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["jobs.job_id"],
        ),
        sa.PrimaryKeyConstraint("spec_version_id"),
        sa.UniqueConstraint("job_id", "version", name="uq_spec_job_version"),
    )
    op.create_table(
        "validations",
        sa.Column("validation_id", sa.String(length=64), nullable=False),
        sa.Column("job_id", sa.String(length=64), nullable=False),
        sa.Column("stage", sa.String(length=32), nullable=False),
        sa.Column("plan_hash", sa.String(length=80), nullable=True),
        sa.Column("report_json", sa.JSON(), nullable=False),
        sa.Column("blocking_count", sa.Integer(), nullable=False),
        sa.Column("error_count", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["jobs.job_id"],
        ),
        sa.PrimaryKeyConstraint("validation_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # Only ship a downgrade you have tested against real data.
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("validations")
    op.drop_table("spec_versions")
    op.drop_table("plans")
    op.drop_table("executions")
    op.drop_table("checkpoints")
    op.drop_table("approvals")
    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_jobs_plan_hash"))

    op.drop_table("jobs")
    with op.batch_alter_table("entity_mappings", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_entity_mappings_feature_id"))
        batch_op.drop_index(batch_op.f("ix_entity_mappings_document_id"))

    op.drop_table("entity_mappings")
    op.drop_table("documents")
    with op.batch_alter_table("audit_events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_audit_events_job_id"))

    op.drop_table("audit_events")
    # ### end Alembic commands ###
