using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using System.Text.Json.Nodes;
using CadBridge.Contracts;
using CadBridge.Hosting;
using CadBridge.Ipc;
using Xunit;

namespace CadBridge.Tests;

public sealed class BridgeRequestRouterTests
{
    private const string CrossLanguagePlanHash =
        "sha256:40289068e3b4f14a42f0e03392c39e4b807e4b6d2850a7ca1012087f01a42275";

    private const string CrossLanguageApprovalToken =
        "v2.eyJhcHByb3ZhbF9pZCI6ImFwcHJvdmFsX2ZpeGVkIiwiYXBwcm92ZWRfYnkiOiJlbmdpbmVlckBleGFtcGxlLmNvbSIsImRvY3VtZW50X2lkIjoiZG9jXzEiLCJleHBlY3RlZF9yZXZpc2lvbiI6InNoYTI1NjpyZXZpc2lvbiIsImV4cGlyZXNfYXQiOiIyMDMwLTAxLTAxVDAwOjE1OjAwKzAwOjAwIiwiam9iX2lkIjoiam9iXzEiLCJwbGFuX2hhc2giOiJzaGEyNTY6NDAyODkwNjhlM2I0ZjE0YTQyZjBlMDMzOTJjMzllNGI4MDdlNGI2ZDI4NTBhN2NhMTAxMjA4N2YwMWE0MjI3NSJ9.8137d55394d58d2caf95591068ab4baf6d21b1aedc2c7745836d614d40640d79";

    // Generated by src/cad_harness/security/rollback_approval.py with a fixed UTC record.
    private const string CrossLanguageRollbackApprovalToken =
        "rb1.eyJhcHByb3ZhbF9pZCI6InJvbGxiYWNrX2FwcHJvdmFsX2ZpeGVkIiwiYXBwcm92ZWRfYXQiOiIyMDMwLTAxLTAxVDAwOjAwOjAwKzAwOjAwIiwiYXBwcm92ZWRfYnkiOiJlbmdpbmVlckBleGFtcGxlLmNvbSIsImNoZWNrcG9pbnRfaWQiOiJjaGVja3BvaW50X2ZpeGVkIiwiY3VycmVudF9yZXZpc2lvbiI6InNoYTI1NjpjdXJyZW50LXJldmlzaW9uIiwiZG9jdW1lbnRfaWQiOiJkb2Nfcm9sbGJhY2tfMSIsImV4cGlyZXNfYXQiOiIyMDMwLTAxLTAxVDAwOjE1OjAwKzAwOjAwIiwiam9iX2lkIjoiam9iX3JvbGxiYWNrXzEiLCJzY2hlbWFfdmVyc2lvbiI6IjEuMTMifQ.dad3b2b209d472c64e396c9203c60f3ffbbfb7b584ca900087fad6b099822d46";

    private const string PreviousSchemaRollbackApprovalToken =
        "rb1.eyJhcHByb3ZhbF9pZCI6InJvbGxiYWNrX2FwcHJvdmFsX2ZpeGVkIiwiYXBwcm92ZWRfYXQiOiIyMDMwLTAxLTAxVDAwOjAwOjAwKzAwOjAwIiwiYXBwcm92ZWRfYnkiOiJlbmdpbmVlckBleGFtcGxlLmNvbSIsImNoZWNrcG9pbnRfaWQiOiJjaGVja3BvaW50X2ZpeGVkIiwiY3VycmVudF9yZXZpc2lvbiI6InNoYTI1NjpjdXJyZW50LXJldmlzaW9uIiwiZG9jdW1lbnRfaWQiOiJkb2Nfcm9sbGJhY2tfMSIsImV4cGlyZXNfYXQiOiIyMDMwLTAxLTAxVDAwOjE1OjAwKzAwOjAwIiwiam9iX2lkIjoiam9iX3JvbGxiYWNrXzEiLCJzY2hlbWFfdmVyc2lvbiI6IjEuMTIifQ.9847105aea7db284bcc7124a9d7181c77a47b02d9495c5c57ac6e1f20d3c3a1f";

    [Fact]
    public void ApprovalAndPlanHashMatchPythonCanonicalContractAtExactExpiryBoundary()
    {
        using var source = JsonDocument.Parse(
            """
            {"canonical_units":"mm","document_id":"doc_1","expected_revision":"sha256:revision","job_id":"job_1","operations":[{"expected":{"length_mm":2.352},"feature_id":"feat_\u03b1","geometry":{"end_mm":[1.2345678916,2.0],"start_mm":[0.0,-0.0]},"layer":"CUT","operation_id":"op_1","target_entity_ref":null,"type":"create_line"}],"plan_hash":"sha256:40289068e3b4f14a42f0e03392c39e4b807e4b6d2850a7ca1012087f01a42275","plan_id":"plan_1","profile_ref":"demo@1.0","schema_version":"1.13","validation_expectations":[]}
            """);
        var plan = source.RootElement.Clone();

        Assert.Equal(CrossLanguagePlanHash, BridgeAuthorization.ComputePlanHash(plan));
        Assert.True(BridgeAuthorization.TryValidateCommitAuthorization(
            plan,
            CrossLanguageApprovalToken,
            "cross-language-secret",
            "job_1",
            "sha256:revision",
            new DateTimeOffset(2030, 1, 1, 0, 15, 0, TimeSpan.Zero),
            out var claims));
        Assert.NotNull(claims);
        Assert.Equal("approval_fixed", claims.ApprovalId);

        Assert.False(BridgeAuthorization.TryValidateCommitAuthorization(
            plan,
            CrossLanguageApprovalToken,
            "cross-language-secret",
            "job_1",
            "sha256:revision",
            new DateTimeOffset(2030, 1, 1, 0, 15, 0, TimeSpan.Zero).AddTicks(1),
            out _));
    }

    [Fact]
    public void CommitAuthorizationRejectsValidlyHashedAndSignedPreviousSchemaPlan()
    {
        const string secret = "previous-schema-secret";
        var planNode = JsonNode.Parse(
            """
            {"canonical_units":"mm","document_id":"doc_legacy","expected_revision":"sha256:revision","job_id":"job_legacy","operations":[],"plan_hash":null,"plan_id":"plan_legacy","profile_ref":"demo@1.0","schema_version":"1.12","validation_expectations":[]}
            """)!.AsObject();
        using (var unhashed = JsonDocument.Parse(planNode.ToJsonString()))
        {
            planNode["plan_hash"] = BridgeAuthorization.ComputePlanHash(unhashed.RootElement);
        }
        var planHash = planNode["plan_hash"]!.GetValue<string>();
        var expiresAt = new DateTimeOffset(2030, 1, 1, 0, 15, 0, TimeSpan.Zero);
        var claims = new JsonObject
        {
            ["approval_id"] = "approval_legacy",
            ["job_id"] = "job_legacy",
            ["document_id"] = "doc_legacy",
            ["expected_revision"] = "sha256:revision",
            ["plan_hash"] = planHash,
            ["approved_by"] = "engineer@example.com",
            ["expires_at"] = expiresAt.ToString("O"),
        };
        var payload = Convert.ToBase64String(Encoding.UTF8.GetBytes(claims.ToJsonString()))
            .TrimEnd('=')
            .Replace('+', '-')
            .Replace('/', '_');
        var signature = Convert.ToHexString(HMACSHA256.HashData(
            Encoding.UTF8.GetBytes(secret),
            Encoding.ASCII.GetBytes(payload))).ToLowerInvariant();
        using var planDocument = JsonDocument.Parse(planNode.ToJsonString());

        Assert.False(BridgeAuthorization.TryValidateCommitAuthorization(
            planDocument.RootElement,
            $"v2.{payload}.{signature}",
            secret,
            "job_legacy",
            "sha256:revision",
            expiresAt,
            out _));
    }

    [Fact]
    public void RollbackApprovalMatchesPythonContractAtExactExpiryBoundary()
    {
        var expiry = new DateTimeOffset(2030, 1, 1, 0, 15, 0, TimeSpan.Zero);
        Assert.True(BridgeAuthorization.TryValidateRollbackAuthorization(
            CrossLanguageRollbackApprovalToken,
            "cross-language-rollback-secret",
            "job_rollback_1",
            "doc_rollback_1",
            "checkpoint_fixed",
            "sha256:current-revision",
            expiry,
            out var claims));
        Assert.NotNull(claims);
        Assert.Equal("rollback_approval_fixed", claims.ApprovalId);
        Assert.Equal("1.13", claims.SchemaVersion);

        Assert.False(BridgeAuthorization.TryValidateRollbackAuthorization(
            CrossLanguageRollbackApprovalToken,
            "cross-language-rollback-secret",
            "job_rollback_1",
            "doc_rollback_1",
            "checkpoint_fixed",
            "sha256:current-revision",
            expiry.AddTicks(1),
            out _));
    }

    [Fact]
    public void ExpiredRollbackApprovalRequiresExactRecordedAttemptProof()
    {
        const string secret = "cross-language-rollback-secret";
        var expiry = new DateTimeOffset(2030, 1, 1, 0, 15, 0, TimeSpan.Zero);
        var proofCalls = 0;

        Assert.True(BridgeAuthorization.TryValidateRollbackRecoveryAuthorization(
            CrossLanguageRollbackApprovalToken,
            secret,
            "job_rollback_1",
            "doc_rollback_1",
            "checkpoint_fixed",
            "sha256:current-revision",
            expiry.AddTicks(1),
            claims =>
            {
                proofCalls++;
                return claims.ApprovalId == "rollback_approval_fixed";
            },
            out var claims));
        Assert.NotNull(claims);
        Assert.Equal(1, proofCalls);

        Assert.False(BridgeAuthorization.TryValidateRollbackRecoveryAuthorization(
            CrossLanguageRollbackApprovalToken,
            secret,
            "job_rollback_1",
            "doc_rollback_1",
            "checkpoint_fixed",
            "sha256:current-revision",
            expiry.AddTicks(1),
            _ => false,
            out _));

        var beforeRejectedTokens = proofCalls;
        Assert.False(BridgeAuthorization.TryValidateRollbackRecoveryAuthorization(
            CrossLanguageRollbackApprovalToken,
            secret,
            "job_rollback_1-changed",
            "doc_rollback_1",
            "checkpoint_fixed",
            "sha256:current-revision",
            expiry.AddTicks(1),
            _ =>
            {
                proofCalls++;
                return true;
            },
            out _));
        var parts = CrossLanguageRollbackApprovalToken.Split('.');
        Assert.False(BridgeAuthorization.TryValidateRollbackRecoveryAuthorization(
            $"rb1.{parts[1]}.{parts[2][..^1]}0",
            secret,
            "job_rollback_1",
            "doc_rollback_1",
            "checkpoint_fixed",
            "sha256:current-revision",
            expiry.AddTicks(1),
            _ =>
            {
                proofCalls++;
                return true;
            },
            out _));
        Assert.Equal(beforeRejectedTokens, proofCalls);

        Assert.False(BridgeAuthorization.TryValidateRollbackRecoveryAuthorization(
            CrossLanguageRollbackApprovalToken,
            secret,
            "job_rollback_1",
            "doc_rollback_1",
            "checkpoint_fixed",
            "sha256:current-revision",
            expiry,
            _ =>
            {
                proofCalls++;
                return true;
            },
            out _));
        Assert.Equal(beforeRejectedTokens, proofCalls);
    }

    [Fact]
    public void RollbackApprovalFailsClosedForNamespaceSignatureAndScopeMismatch()
    {
        const string secret = "cross-language-rollback-secret";
        var scope = new[]
        {
            "job_rollback_1",
            "doc_rollback_1",
            "checkpoint_fixed",
            "sha256:current-revision",
        };
        var now = new DateTimeOffset(2030, 1, 1, 0, 0, 0, TimeSpan.Zero);
        var parts = CrossLanguageRollbackApprovalToken.Split('.');

        Assert.False(BridgeAuthorization.TryValidateRollbackAuthorization(
            $"v2.{parts[1]}.{parts[2]}", secret, scope[0], scope[1], scope[2], scope[3], now, out _));
        Assert.False(BridgeAuthorization.TryValidateRollbackAuthorization(
            $"rb1.{parts[1]}.{parts[2][..^1]}0", secret, scope[0], scope[1], scope[2], scope[3], now, out _));
        Assert.False(BridgeAuthorization.TryValidateRollbackAuthorization(
            PreviousSchemaRollbackApprovalToken,
            secret,
            scope[0],
            scope[1],
            scope[2],
            scope[3],
            now,
            out _));

        for (var index = 0; index < scope.Length; index++)
        {
            var changed = (string[])scope.Clone();
            changed[index] += "-changed";
            Assert.False(BridgeAuthorization.TryValidateRollbackAuthorization(
                CrossLanguageRollbackApprovalToken,
                secret,
                changed[0],
                changed[1],
                changed[2],
                changed[3],
                now,
                out _));
        }
    }

    [Fact]
    public void WholeNumberFloatPlanHashMatchesPythonCanonicalContract()
    {
        using var source = JsonDocument.Parse(
            """
            {"schema_version":"1.13","plan_id":"plan_diag_001","job_id":"job_diag_001","document_id":"doc_live","expected_revision":"sha256:revision","canonical_units":"mm","profile_ref":"live-r26","operations":[{"operation_id":"op_diag_001","feature_id":"feature_diag_001","type":"create_line","layer":"0","geometry":{"start_mm":[0.0,0.0],"end_mm":[1.0,0.0]},"expected":{},"target_entity_ref":null}],"validation_expectations":[],"plan_hash":null}
            """);

        Assert.Equal(
            "sha256:b5d1ec28ed7cdfbf9e69a7261df57d05d77324cedd3d6853d0166176e1fd2c38",
            BridgeAuthorization.ComputePlanHash(source.RootElement));
    }

    [Fact]
    public async Task HandshakeAndStatusDeclareOnlyValidatedHostFacts()
    {
        var host = new FakeBridgeHost(DefaultDescriptor() with
        {
            Capabilities =
            [
                "stable_metadata",
                "commit",
                "document_lock",
                "atomic_transaction",
                "undo_group",
                "inspect_document",
            ],
            SupportedOperationTypes = ["create_line"],
        })
        {
            Status = new BridgeHostStatus(true, "doc-active", "ready"),
        };
        var router = new BridgeRequestRouter(host);

        var handshake = await router.HandleAsync(
            Request("handshake", new JsonObject { ["schema_version"] = "1.13" }),
            CancellationToken.None);

        Assert.Equal(IpcResponseStatus.Ok, handshake.Status);
        Assert.Equal("1.13", handshake.Data!["schema_version"]!.GetValue<string>());
        Assert.Equal(
            [
                "atomic_transaction",
                "commit",
                "document_lock",
                "inspect_document",
                "stable_metadata",
                "undo_group",
            ],
            Strings(handshake.Data["capabilities"]));
        Assert.Equal(["create_line"], Strings(handshake.Data["supported_operations"]));
        Assert.Equal("AutoCAD", handshake.Data["cad_application"]!.GetValue<string>());
        Assert.Equal("25.1", handshake.Data["cad_version"]!.GetValue<string>());
        Assert.Empty(host.Calls);

        var status = await router.HandleAsync(
            Request("status", new JsonObject()),
            CancellationToken.None);
        Assert.Equal(IpcResponseStatus.Ok, status.Status);
        Assert.True(status.Data!["available"]!.GetValue<bool>());
        Assert.Equal("doc-active", status.Data["active_document_id"]!.GetValue<string>());
        Assert.Equal("ready", status.Data["message"]!.GetValue<string>());
        Assert.Equal(["status"], host.Calls.Select(call => call.Route));
    }

    [Fact]
    public async Task NullOptionalEnvelopeFieldsMatchTheIpcContract()
    {
        var host = new FakeBridgeHost(DefaultDescriptor())
        {
            Status = new BridgeHostStatus(true, "doc-active", "ready"),
        };
        var router = new BridgeRequestRouter(host);
        var handshake = JsonSerializer.SerializeToElement(new JsonObject
        {
            ["schema_version"] = "1.13",
            ["method"] = "handshake",
            ["request_id"] = "request-handshake-null-optionals",
            ["params"] = new JsonObject { ["schema_version"] = "1.13" },
            ["job_id"] = null,
            ["idempotency_key"] = null,
        });
        var status = JsonSerializer.SerializeToElement(new JsonObject
        {
            ["schema_version"] = "1.13",
            ["method"] = "status",
            ["request_id"] = "request-status-null-optionals",
            ["params"] = new JsonObject(),
            ["job_id"] = null,
            ["idempotency_key"] = null,
        });

        var handshakeResult = await router.HandleAsync(handshake, CancellationToken.None);
        var statusResult = await router.HandleAsync(status, CancellationToken.None);

        Assert.Equal(IpcResponseStatus.Ok, handshakeResult.Status);
        Assert.Equal(IpcResponseStatus.Ok, statusResult.Status);
        Assert.Equal(["status"], host.Calls.Select(call => call.Route));
    }

    [Theory]
    [MemberData(nameof(InvalidRequestCases))]
    public async Task MissingOrUnknownParametersAreRejectedBeforeHostCall(
        string method,
        string parametersJson,
        bool addUnknownEnvelopeProperty)
    {
        var host = new FakeBridgeHost(DefaultDescriptor());
        var envelope = JsonNode.Parse(
            JsonSerializer.Serialize(Request(method, JsonNode.Parse(parametersJson)!.AsObject())))!
            .AsObject();
        if (addUnknownEnvelopeProperty)
        {
            envelope["unknown"] = true;
        }

        var result = await new BridgeRequestRouter(host).HandleAsync(
            JsonSerializer.SerializeToElement(envelope),
            CancellationToken.None);

        Assert.Equal(IpcResponseStatus.Rejected, result.Status);
        Assert.Equal("INVALID_FEATURE_PARAMETERS", result.Error!.Code);
        Assert.Empty(host.Calls);
    }

    public static TheoryData<string, string, bool> InvalidRequestCases => new()
    {
        { "status", "{\"extra\":true}", false },
        {
            "inspect_document",
            "{\"document_id\":\"doc-1\",\"include_layers\":true}",
            false
        },
        {
            "inspect_selection",
            "{\"document_id\":\"doc-1\",\"max_entities\":0}",
            false
        },
        {
            "validate_revision",
            "{\"document_id\":\"doc-1\",\"expected_revision\":\"rev\",\"extra\":0}",
            false
        },
        {
            "export",
            "{\"document_id\":\"doc-1\",\"format\":\"exe\",\"target_path\":\"out.exe\",\"overwrite\":false}",
            false
        },
        { "status", "{}", true },
    };

    [Fact]
    public async Task EveryTypedRouteBindsExactRecordsAndPropagatesCancellationToken()
    {
        var host = new FakeBridgeHost(DefaultDescriptor());
        var router = new BridgeRequestRouter(host);
        using var cancellation = new CancellationTokenSource();
        var token = cancellation.Token;
        var plan = Plan("job-typed");

        Assert.Equal(
            IpcResponseStatus.Ok,
            (await router.HandleAsync(Request("status", new JsonObject()), token)).Status);
        Assert.Equal(
            IpcResponseStatus.Ok,
            (await router.HandleAsync(
                Request("inspect_document", new JsonObject
                {
                    ["document_id"] = "doc-1",
                    ["include_layers"] = true,
                    ["include_styles"] = false,
                }),
                token)).Status);
        Assert.Equal(
            IpcResponseStatus.Ok,
            (await router.HandleAsync(
                Request("inspect_selection", new JsonObject
                {
                    ["document_id"] = "doc-1",
                    ["max_entities"] = 42,
                }),
                token)).Status);
        Assert.Equal(
            IpcResponseStatus.Ok,
            (await router.HandleAsync(Request("preview", plan.DeepClone().AsObject()), token)).Status);
        Assert.Equal(
            IpcResponseStatus.Ok,
            (await router.HandleAsync(
                Request("validate_revision", new JsonObject
                {
                    ["document_id"] = "doc-1",
                    ["expected_revision"] = "sha256:before",
                }),
                token)).Status);
        Assert.Equal(
            IpcResponseStatus.Ok,
            (await router.HandleAsync(
                Request(
                    "commit",
                    CommitParameters(plan.DeepClone().AsObject(), "idem-1", "sha256:before"),
                    jobId: "job-typed",
                    idempotencyKey: "idem-1"),
                token)).Status);
        Assert.Equal(
            IpcResponseStatus.Ok,
            (await router.HandleAsync(
                Request(
                    "rollback",
                    new JsonObject
                    {
                        ["job_id"] = "job-typed",
                        ["document_id"] = "doc-1",
                        ["checkpoint_id"] = "checkpoint-1",
                        ["current_revision"] = "sha256:current",
                        ["rollback_approval_token"] = "rb1.opaque.signature",
                        ["undo_group"] = "undo-group-typed",
                    },
                    jobId: "job-typed"),
                token)).Status);
        Assert.Equal(
            IpcResponseStatus.Ok,
            (await router.HandleAsync(
                Request("export", new JsonObject
                {
                    ["document_id"] = "doc-1",
                    ["format"] = "dxf",
                    ["target_path"] = "C:/approved/out.dxf",
                    ["overwrite"] = false,
                }),
                token)).Status);

        Assert.Equal(
            [
                "status",
                "inspect_document",
                "inspect_selection",
                "preview",
                "validate_revision",
                "commit",
                "rollback",
                "export",
            ],
            host.Calls.Select(call => call.Route));
        Assert.All(host.Calls, call => Assert.Equal(token, call.CancellationToken));
        Assert.Equal(
            new InspectDocumentHostRequest("doc-1", true, false),
            Assert.IsType<InspectDocumentHostRequest>(host.Calls[1].Request));
        Assert.Equal(
            new InspectSelectionHostRequest("doc-1", 42),
            Assert.IsType<InspectSelectionHostRequest>(host.Calls[2].Request));
        Assert.Equal(
            "job-typed",
            Assert.IsType<PreviewHostRequest>(host.Calls[3].Request).JobId);
        Assert.Equal(
            new RevisionValidationHostRequest("doc-1", "sha256:before"),
            Assert.IsType<RevisionValidationHostRequest>(host.Calls[4].Request));
        var commit = Assert.IsType<CommitHostRequest>(host.Calls[5].Request);
        Assert.Equal("job-typed", commit.JobId);
        Assert.Equal("idem-1", commit.IdempotencyKey);
        Assert.Equal("sha256:before", commit.ExpectedRevision);
        Assert.Equal("approval-1", commit.ApprovalToken);
        Assert.True(commit.CreateCheckpoint);
        Assert.Equal(
            new RollbackHostRequest(
                "job-typed",
                "doc-1",
                "checkpoint-1",
                "sha256:current",
                "rb1.opaque.signature",
                "undo-group-typed"),
            Assert.IsType<RollbackHostRequest>(host.Calls[6].Request));
        Assert.Equal(
            new ExportHostRequest("doc-1", "dxf", "C:/approved/out.dxf", false),
            Assert.IsType<ExportHostRequest>(host.Calls[7].Request));
    }

    [Fact]
    public async Task SemanticSummaryAndModelDispatchToTypedHostBoundary()
    {
        var host = new FakeBridgeHost(DefaultDescriptor());
        var router = new BridgeRequestRouter(host);
        using var cancellation = new CancellationTokenSource();

        var summary = await router.HandleAsync(
            Request("inspect_document", SemanticParameters("drawing_summary", scope: null)),
            cancellation.Token);
        var model = await router.HandleAsync(
            Request(
                "inspect_document",
                SemanticParameters(
                    "drawing_model",
                    new JsonObject
                    {
                        ["kind"] = "layer",
                        ["layer_name"] = "CUT",
                        ["layout_name"] = null,
                        ["entity_refs"] = new JsonArray(),
                    })),
            cancellation.Token);

        Assert.Equal(IpcResponseStatus.Ok, summary.Status);
        Assert.Equal(IpcResponseStatus.Ok, model.Status);
        Assert.Equal(["semantic_drawing", "semantic_drawing"], host.Calls.Select(call => call.Route));
        Assert.All(host.Calls, call => Assert.Equal(cancellation.Token, call.CancellationToken));

        var summaryRequest = Assert.IsType<SemanticDrawingHostRequest>(host.Calls[0].Request);
        Assert.Equal(
            new SemanticDrawingSourceHostRequest("active_document", "dwg", "doc-1"),
            summaryRequest.Source);
        Assert.Null(summaryRequest.Scope);
        Assert.Equal(250, summaryRequest.MaxEntities);
        Assert.Equal(4, summaryRequest.MaxBlockNestingDepth);
        Assert.True(summaryRequest.IncludeGeometry);
        Assert.Equal(
            SemanticDrawingResponseContract.DrawingSummary,
            summaryRequest.ResponseContract);

        var modelRequest = Assert.IsType<SemanticDrawingHostRequest>(host.Calls[1].Request);
        Assert.NotNull(modelRequest.Scope);
        Assert.Equal("layer", modelRequest.Scope.Kind);
        Assert.Equal("CUT", modelRequest.Scope.LayerName);
        Assert.Null(modelRequest.Scope.LayoutName);
        Assert.Empty(modelRequest.Scope.EntityRefs);
        Assert.Equal(SemanticDrawingResponseContract.DrawingModel, modelRequest.ResponseContract);
    }

    [Theory]
    [MemberData(nameof(MalformedSemanticParameters))]
    public async Task MalformedSemanticReadIsRejectedBeforeHostCall(string parametersJson)
    {
        var host = new FakeBridgeHost(DefaultDescriptor());
        var result = await new BridgeRequestRouter(host).HandleAsync(
            Request("inspect_document", JsonNode.Parse(parametersJson)!.AsObject()),
            CancellationToken.None);

        Assert.Equal(IpcResponseStatus.Rejected, result.Status);
        Assert.Equal("INVALID_FEATURE_PARAMETERS", result.Error!.Code);
        Assert.Empty(host.Calls);
    }

    public static TheoryData<string> MalformedSemanticParameters => new()
    {
        { SemanticJson("drawing_summary", "null", source: "{\"kind\":\"file\",\"format\":\"dwg\",\"ref\":\"doc-1\"}") },
        { SemanticJson("drawing_summary", "null", source: "{\"kind\":\"active_document\",\"format\":\"pdf\",\"ref\":\"doc-1\"}") },
        { SemanticJson("unknown_contract", "null") },
        { SemanticJson("drawing_model", "null") },
        { SemanticJson("drawing_summary", "{\"kind\":\"layer\",\"layer_name\":null,\"layout_name\":null,\"entity_refs\":[]}") },
        { SemanticJson("drawing_summary", "{\"kind\":\"selection\",\"layer_name\":null,\"layout_name\":null,\"entity_refs\":[\"acad:1\",\"acad:1\"]}") },
        { SemanticJson("drawing_summary", "{\"kind\":\"selection\",\"layer_name\":null,\"layout_name\":null,\"entity_refs\":[\"acad:1\",\"acad:2\"]}", maxEntities: 1) },
        { SemanticJson("drawing_summary", "{\"kind\":\"model_space\",\"layer_name\":null,\"layout_name\":null}") },
        { SemanticJson("drawing_summary", "null", maxEntities: 0) },
        { SemanticJson("drawing_summary", "null", maxDepth: 11) },
        { SemanticJson("drawing_summary", "null", includeGeometryJson: "\"yes\"") },
        { SemanticJson("drawing_summary", "null", extraTopLevel: ",\"unknown\":true") },
    };

    [Fact]
    public async Task CancellationStopsRoutingBeforeHostAndDirectCancelIsNeverHostRouted()
    {
        var host = new FakeBridgeHost(DefaultDescriptor());
        var router = new BridgeRequestRouter(host);
        using var cancellation = new CancellationTokenSource();
        cancellation.Cancel();

        await Assert.ThrowsAnyAsync<OperationCanceledException>(
            () => router.HandleAsync(
                Request("status", new JsonObject()),
                cancellation.Token).AsTask());
        Assert.Empty(host.Calls);

        var directCancel = await router.HandleAsync(
            Request("cancel", new JsonObject { ["target_request_id"] = "target-1" }),
            CancellationToken.None);
        Assert.Equal(IpcResponseStatus.Rejected, directCancel.Status);
        Assert.Equal("UNSUPPORTED_FEATURE", directCancel.Error!.Code);
        Assert.Equal("Cancellation is owned by the IPC processor.", directCancel.Error.Message);
        Assert.Empty(host.Calls);
    }

    [Fact]
    public async Task UnsupportedCapabilityOrOperationNeverCallsHost()
    {
        var noPreviewHost = new FakeBridgeHost(DefaultDescriptor() with
        {
            Capabilities = DefaultDescriptor().Capabilities
                .Where(capability => capability != "preview")
                .ToArray(),
        });
        var noPreview = await new BridgeRequestRouter(noPreviewHost).HandleAsync(
            Request("preview", Plan("job-preview")),
            CancellationToken.None);
        Assert.Equal("ADAPTER_CAPABILITY_MISSING", noPreview.Error!.Code);
        Assert.Empty(noPreviewHost.Calls);

        foreach (var operationType in new[] { "create_circle", "launch_process" })
        {
            var host = new FakeBridgeHost(DefaultDescriptor());
            var result = await new BridgeRequestRouter(host).HandleAsync(
                Request("preview", Plan("job-op", operationType)),
                CancellationToken.None);
            Assert.Equal(IpcResponseStatus.Rejected, result.Status);
            Assert.Equal("INVALID_FEATURE_PARAMETERS", result.Error!.Code);
            Assert.Empty(host.Calls);
        }
    }

    [Theory]
    [InlineData(null, "checkpoint_restore")]
    [InlineData("undo-group-1", "rollback_undo_group")]
    public async Task RollbackSelectsCapabilityAfterParsingUndoGroup(
        string? undoGroup,
        string requiredCapability)
    {
        var host = new FakeBridgeHost(new BridgeHostDescriptor(
            "AutoCAD",
            "25.1",
            [requiredCapability],
            []));
        var envelope = new JsonObject
        {
            ["schema_version"] = "1.13",
            ["method"] = "rollback",
            ["request_id"] = "request-rollback-route",
            ["params"] = RollbackParameters("job-rollback-route", undoGroup),
            ["job_id"] = "job-rollback-route",
            ["idempotency_key"] = null,
        };

        var result = await new BridgeRequestRouter(host).HandleAsync(
            JsonSerializer.SerializeToElement(envelope),
            CancellationToken.None);

        Assert.Equal(IpcResponseStatus.Ok, result.Status);
        var call = Assert.Single(host.Calls);
        Assert.Equal("rollback", call.Route);
        Assert.Equal(
            new RollbackHostRequest(
                "job-rollback-route",
                "doc-1",
                "checkpoint-1",
                "sha256:current",
                "rb1.opaque.signature",
                undoGroup),
            Assert.IsType<RollbackHostRequest>(call.Request));
    }

    [Theory]
    [InlineData(null, "rollback_undo_group")]
    [InlineData("undo-group-1", "checkpoint_restore")]
    public async Task RollbackMissingSelectedCapabilityNeverCallsHost(
        string? undoGroup,
        string otherCapability)
    {
        var host = new FakeBridgeHost(new BridgeHostDescriptor(
            "AutoCAD",
            "25.1",
            [otherCapability],
            []));

        var result = await new BridgeRequestRouter(host).HandleAsync(
            Request(
                "rollback",
                RollbackParameters("job-rollback-missing-capability", undoGroup),
                jobId: "job-rollback-missing-capability"),
            CancellationToken.None);

        Assert.Equal(IpcResponseStatus.Rejected, result.Status);
        Assert.Equal("ADAPTER_CAPABILITY_MISSING", result.Error!.Code);
        Assert.Empty(host.Calls);
    }

    [Theory]
    [InlineData("wrong-envelope-job", "undo-group-1")]
    [InlineData("job-rollback-invalid", 42)]
    public async Task InvalidRollbackBindingOrUndoGroupIsRejectedBeforeCapabilityOrHost(
        string envelopeJobId,
        object undoGroup)
    {
        var host = new FakeBridgeHost(new BridgeHostDescriptor(
            "AutoCAD",
            "25.1",
            [],
            []));
        var parameters = RollbackParameters("job-rollback-invalid", "undo-group-1");
        parameters["undo_group"] = JsonValue.Create(undoGroup);

        var result = await new BridgeRequestRouter(host).HandleAsync(
            Request("rollback", parameters, jobId: envelopeJobId),
            CancellationToken.None);

        Assert.Equal(IpcResponseStatus.Rejected, result.Status);
        Assert.Equal("INVALID_FEATURE_PARAMETERS", result.Error!.Code);
        Assert.Empty(host.Calls);
    }

    [Theory]
    [InlineData(BridgeHostOutcome.StaleDocumentRevision, IpcResponseStatus.Conflict, "STALE_DOCUMENT_REVISION", "Read the document again and compile a new plan.", false)]
    [InlineData(BridgeHostOutcome.UnknownCommitState, IpcResponseStatus.Failed, "UNKNOWN_COMMIT_STATE", "Reconcile the job before any further commit attempt.", false)]
    [InlineData(BridgeHostOutcome.RollbackRecoveryRequired, IpcResponseStatus.Failed, "ROLLBACK_RECOVERY_REQUIRED", "Retry the exact rollback with its original in-memory approval and scope.", true)]
    [InlineData(BridgeHostOutcome.Conflict, IpcResponseStatus.Conflict, "WRITER_LEASE_CONFLICT", null, true)]
    [InlineData(BridgeHostOutcome.IdempotencyKeyReused, IpcResponseStatus.Conflict, "IDEMPOTENCY_KEY_REUSED", null, false)]
    [InlineData(BridgeHostOutcome.Failed, IpcResponseStatus.Failed, "COM_CALL_FAILED", null, false)]
    public async Task HostFailuresPreserveTerminalStatusAndSafeErrorFidelity(
        BridgeHostOutcome outcome,
        IpcResponseStatus expectedStatus,
        string expectedCode,
        string? expectedAction,
        bool expectedRetryable)
    {
        var host = new FakeBridgeHost(DefaultDescriptor());
        host.Results["commit"] = new BridgeHostResult(outcome);
        var plan = Plan("job-error");

        var result = await new BridgeRequestRouter(host).HandleAsync(
            Request(
                "commit",
                CommitParameters(plan, "idem-error", "sha256:before"),
                jobId: "job-error",
                idempotencyKey: "idem-error"),
            CancellationToken.None);

        Assert.Equal(expectedStatus, result.Status);
        Assert.Null(result.Data);
        Assert.Equal(expectedCode, result.Error!.Code);
        Assert.Equal(expectedAction, result.Error.RequiredAction);
        Assert.Equal(expectedRetryable, result.Error.Retryable);
        Assert.Single(host.Calls);
    }

    [Theory]
    [InlineData("wrong-job", "idem-1")]
    [InlineData("job-1", "wrong-idempotency")]
    public async Task CommitEnvelopeMustCorrelateJobAndIdempotencyBeforeHostCall(
        string envelopeJobId,
        string envelopeIdempotencyKey)
    {
        var host = new FakeBridgeHost(DefaultDescriptor());
        var plan = Plan("job-1");

        var result = await new BridgeRequestRouter(host).HandleAsync(
            Request(
                "commit",
                CommitParameters(plan, "idem-1", "sha256:before"),
                jobId: envelopeJobId,
                idempotencyKey: envelopeIdempotencyKey),
            CancellationToken.None);

        Assert.Equal(IpcResponseStatus.Rejected, result.Status);
        Assert.Equal("INVALID_FEATURE_PARAMETERS", result.Error!.Code);
        Assert.Empty(host.Calls);
    }

    [Theory]
    [InlineData("missing-atomic")]
    [InlineData("operations-without-commit")]
    [InlineData("duplicate-capability")]
    public void InvalidCapabilityDeclarationsFailAtConstruction(string scenario)
    {
        var descriptor = scenario switch
        {
            "missing-atomic" => DefaultDescriptor() with
            {
                Capabilities = ["commit", "document_lock", "undo_group", "stable_metadata"],
            },
            "operations-without-commit" => DefaultDescriptor() with
            {
                Capabilities = ["inspect_document"],
            },
            "duplicate-capability" => DefaultDescriptor() with
            {
                Capabilities = ["inspect_document", "inspect_document"],
                SupportedOperationTypes = [],
            },
            _ => throw new Xunit.Sdk.XunitException("Unknown descriptor scenario."),
        };

        Assert.Throws<ArgumentException>(() => new BridgeRequestRouter(new FakeBridgeHost(descriptor)));
    }

    private static BridgeHostDescriptor DefaultDescriptor() => new(
        "AutoCAD",
        "25.1",
        [
            "inspect_document",
            "inspect_selection",
            "preview",
            "commit",
            "export",
            "atomic_transaction",
            "document_lock",
            "undo_group",
            "stable_metadata",
            "rollback_undo_group",
            "in_viewport_preview",
        ],
        ["create_line"]);

    private static JsonObject Plan(string jobId, string operationType = "create_line") => new()
    {
        ["schema_version"] = "1.13",
        ["plan_id"] = "plan-1",
        ["job_id"] = jobId,
        ["document_id"] = "doc-1",
        ["expected_revision"] = "sha256:before",
        ["canonical_units"] = "mm",
        ["profile_ref"] = "demo@1.0",
        ["operations"] = new JsonArray
        {
            new JsonObject
            {
                ["operation_id"] = "op-1",
                ["feature_id"] = "feature-1",
                ["type"] = operationType,
                ["layer"] = "PART",
                ["geometry"] = new JsonObject(),
                ["expected"] = new JsonObject(),
                ["target_entity_ref"] = null,
            },
        },
        ["validation_expectations"] = new JsonArray(),
        ["plan_hash"] = "sha256:plan",
    };

    private static JsonObject CommitParameters(
        JsonObject plan,
        string idempotencyKey,
        string expectedRevision) => new()
        {
            ["plan"] = plan,
            ["idempotency_key"] = idempotencyKey,
            ["expected_revision"] = expectedRevision,
            ["approval_token"] = "approval-1",
            ["create_checkpoint"] = true,
        };

    private static JsonObject RollbackParameters(string jobId, string? undoGroup) => new()
    {
        ["job_id"] = jobId,
        ["document_id"] = "doc-1",
        ["checkpoint_id"] = "checkpoint-1",
        ["current_revision"] = "sha256:current",
        ["rollback_approval_token"] = "rb1.opaque.signature",
        ["undo_group"] = undoGroup,
    };

    private static JsonObject SemanticParameters(
        string responseContract,
        JsonObject? scope) => new()
        {
            ["source"] = new JsonObject
            {
                ["kind"] = "active_document",
                ["format"] = ".DWG",
                ["ref"] = "doc-1",
            },
            ["scope"] = scope,
            ["max_entities"] = 250,
            ["max_block_nesting_depth"] = 4,
            ["include_geometry"] = true,
            ["response_contract"] = responseContract,
        };

    private static string SemanticJson(
        string responseContract,
        string scope,
        string source = "{\"kind\":\"active_document\",\"format\":\"dwg\",\"ref\":\"doc-1\"}",
        int maxEntities = 250,
        int maxDepth = 4,
        string includeGeometryJson = "true",
        string extraTopLevel = "") =>
        $"{{\"source\":{source},\"scope\":{scope},\"max_entities\":{maxEntities}," +
        $"\"max_block_nesting_depth\":{maxDepth},\"include_geometry\":{includeGeometryJson}," +
        $"\"response_contract\":\"{responseContract}\"{extraTopLevel}}}";

    private static JsonElement Request(
        string method,
        JsonObject parameters,
        string? jobId = null,
        string? idempotencyKey = null)
    {
        var envelope = new JsonObject
        {
            ["schema_version"] = "1.13",
            ["method"] = method,
            ["request_id"] = $"request-{method}",
            ["params"] = parameters,
        };
        if (jobId is not null)
        {
            envelope["job_id"] = jobId;
        }

        if (idempotencyKey is not null)
        {
            envelope["idempotency_key"] = idempotencyKey;
        }

        return JsonSerializer.SerializeToElement(envelope);
    }

    private static string[] Strings(JsonNode? node) =>
        node!.AsArray().Select(item => item!.GetValue<string>()).ToArray();

    private sealed record HostCall(
        string Route,
        object? Request,
        CancellationToken CancellationToken);

    private sealed class FakeBridgeHost : IBridgeHost
    {
        public FakeBridgeHost(BridgeHostDescriptor descriptor)
        {
            Descriptor = descriptor;
        }

        public BridgeHostDescriptor Descriptor { get; }

        public BridgeHostStatus Status { get; init; } = new(true, "doc-1");

        public List<HostCall> Calls { get; } = [];

        public Dictionary<string, BridgeHostResult> Results { get; } =
            new(StringComparer.Ordinal);

        public ValueTask<BridgeHostStatus> GetStatusAsync(CancellationToken cancellationToken)
        {
            Calls.Add(new HostCall("status", null, cancellationToken));
            return ValueTask.FromResult(Status);
        }

        public ValueTask<BridgeHostResult> InspectDocumentAsync(
            InspectDocumentHostRequest request,
            CancellationToken cancellationToken) => Record("inspect_document", request, cancellationToken);

        public ValueTask<BridgeHostResult> InspectSemanticDrawingAsync(
            SemanticDrawingHostRequest request,
            CancellationToken cancellationToken) => Record("semantic_drawing", request, cancellationToken);

        public ValueTask<BridgeHostResult> InspectSelectionAsync(
            InspectSelectionHostRequest request,
            CancellationToken cancellationToken) => Record("inspect_selection", request, cancellationToken);

        public ValueTask<BridgeHostResult> PreviewAsync(
            PreviewHostRequest request,
            CancellationToken cancellationToken) => Record("preview", request, cancellationToken);

        public ValueTask<BridgeHostResult> ValidateRevisionAsync(
            RevisionValidationHostRequest request,
            CancellationToken cancellationToken) => Record("validate_revision", request, cancellationToken);

        public ValueTask<BridgeHostResult> CommitAsync(
            CommitHostRequest request,
            CancellationToken cancellationToken) => Record("commit", request, cancellationToken);

        public ValueTask<BridgeHostResult> RollbackAsync(
            RollbackHostRequest request,
            CancellationToken cancellationToken) => Record("rollback", request, cancellationToken);

        public ValueTask<BridgeHostResult> ExportAsync(
            ExportHostRequest request,
            CancellationToken cancellationToken) => Record("export", request, cancellationToken);

        private ValueTask<BridgeHostResult> Record(
            string route,
            object request,
            CancellationToken cancellationToken)
        {
            Calls.Add(new HostCall(route, request, cancellationToken));
            var result = Results.TryGetValue(route, out var configured)
                ? configured
                : BridgeHostResult.Success(new JsonObject { ["route"] = route });
            return ValueTask.FromResult(result);
        }
    }
}
